[package]
name = "sourmash_lib"
version = "0.1.0"
authors = ["Luiz Irber <luiz.irber@gmail.com>"]
build = "build.rs"

[lib]
name = "sourmash_lib"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.3.3"

[dependencies]
sourmash = { git = "https://github.com/luizirber/sourmash-rust.git" }
